FROM golang:1.25.0 as base

FROM base as dev

# Install air for hot reloading
# 
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /app

CMD ["air"]
